services:
  novatus_lp_backend:
    container_name: app
    restart: always
    build:
      dockerfile: docker/Dockerfile.dev
      context: ../
    environment:
      - APP_ENV=${APP_ENV}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - CLIENTX509=${CLIENTX509}
      - PKEYID=${PKEYID}
      - PKEY=${PKEY}
      - GEMAIL=${GEMAIL}
      - GCLIENTID=${GCLIENTID}
      - SPREADID=${SPREADID}
    env_file:
      - ../.env
    volumes:
      - app-cache:/usr/app/
    ports:
      - 8000:8000

volumes:
  app-cache: {}
