name: "Continuous Integration"
on:
  workflow_dispatch:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "release/v*.*.*"
      - "dependabot/**"
env:
  APP_ENV: ${{ secrets.APP_ENV }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.12.0"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.4.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install package and dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip3 install .
  code-quality:
    needs: build
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.12.0"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.4.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install linting dependencies
      run:  |
        python -m pip install --upgrade pip setuptools wheel
        pip3 install ".[linter]"
    - name: Lint with Black
      working-directory: ./src
      run: |
        black --config=../pyproject.toml .
    - name: Lint with Isort
      working-directory: ./src
      run: |
        isort --settings-path=../pyproject.toml .
    - name: Lint with MyPy
      working-directory: ./src
      run: |
        mypy --config-file=../pyproject.toml --pretty .
  security:
    needs: code-quality
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.12.0"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.4.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install testing dependencies
      run:  |
        python -m pip install --upgrade pip setuptools wheel
        pip3 install ".[security]"
    - name: Test application's vulnerability with bandit
      working-directory: ./src
      run: |
        bandit -c ../pyproject.toml -r .
  test:
    needs: code-quality
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.12.0"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.4.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Install testing dependencies
      run:  |
        python -m pip install --upgrade pip setuptools wheel
        pip3 install ".[test]"
    - name: Test with Pytest and Coverage
      run: |
        pytest --cov --cov-report xml .
